### ISSUE TITLE
Missing Or Invalid CAPTCHA

### ISSUE THREAD

**Issue by 4G3NT** [TwosHusbandS/Project-127#85]
![Untitled](https://user-images.githubusercontent.com/76431337/102769017-e8534b80-4336-11eb-8fbe-5596c0c672be.png)
My system time is correct and I'm still getting this error any fix? I don't get this error when I log in Grand Theft Auto V normally just with project 1.27.

**Comment by TwosHusbandS** [comment]
Heyo. Thanks for creating an Issue for this!

The problem is unfortunately on rockstars end. 

Fivem is facing the same problem, and some people are even facing it on the original rockstar Launcher. At this moment we cannot fix this. 

The next Update of P127 (coming soon) will allow you to launch through Social Club and you dont need any logging in into your account, so no captchas!

Have a great day!

**Comment by 4G3NT** [comment]
> Heyo. Thanks for creating an Issue for this!
> 
> The problem is unfortunately on rockstars end.
> 
> Fivem is facing the same problem, and some people are even facing it on the original rockstar Launcher. At this moment we cannot fix this.
> 
> The next Update of P127 (coming soon) will allow you to launch through Social Club and you dont need any logging in into your account, so no captchas!
> 
> Have a great day!

I’m using the epic games version should I use the rockstar social club one?

**Comment by TwosHusbandS** [comment]
> 
> 
> > Heyo. Thanks for creating an Issue for this!
> > The problem is unfortunately on rockstars end.
> > Fivem is facing the same problem, and some people are even facing it on the original rockstar Launcher. At this moment we cannot fix this.
> > The next Update of P127 (coming soon) will allow you to launch through Social Club and you dont need any logging in into your account, so no captchas!
> > Have a great day!
> 
> I’m using the epic games version should I use the rockstar social club one?

Nah, at this moment there is nothing you can do apart from waiting for Rockstar to fix it.

**Comment by TwosHusbandS** [comment]
Rockstar fixed the issue on their end. Closed.
